package com.inventory.config.settings.bean;

public class SettingsValuePojo {

	private int NO_OF_PRECISIONS, UPDATE_RATE_AND_CONV_QTY, CURRENCY_FORMAT,PROFIT_CALCULATION,BARCODE_TYPE,PAYROLL_CALCULATION;
	private int DEFAULT_DATE_SELECTION, STOCK_MANAGEMENT,THEME,
			EXPENDETURE_SHOW_ACCOUNTS;
	private String DATE_FORMAT, SYSTEM_EMAIL, SYSTEM_EMAIL_HOST,
			SYSTEM_EMAIL_PASSWORD, SALES_EMAIL, SALES_EMAIL_HOST,
			SALES_EMAIL_PASSWORD, APPLICATION_EMAIL, APPLICATION_EMAIL_HOST,
			APPLICATION_EMAIL_PASSWORD,ALERT_EMAILIDS;

	private boolean CESS_ENABLED, TAX_ENABLED, KEEP_DELETED_DATA,
			SALE_PRICE_EDITABLE, PAYMENT_BILL_SELECTION_MANDATORY,
			DISABLE_SALES_FOR_CUSTOMERS_UNDER_CR_LIMIT,
			ALERT_FOR_UNDER_CREDIT_LIMIT,
			AUTO_CREATE_SUBGROUP_CODE, USE_SALES_NO_IN_SALES_ORDER,
			KEEP_OTHER_WINDOWS, HIDE_ALERTS, GRADING_ENABLED,AUTO_CREATE_SUPPLIER_CODE,AUTO_CREATE_CUSTOMER_CODE,
//			LOCAL_FOREIGN_TYPE_ENABLED,
			USE_SYSTEM_MAIL_FOR_SEND_CUSTOMERMAIL, RACK_ENABLED,
			USE_GROSS_AND_NET_WEIGHT, MULTIPLE_CURRENCY_ENABLED,
			USE_SALES_RATE_FROM_STOCK, SHOW_STOCK_IN_PROFIT_REPORT,
			SALES_NO_CREATION_MANUAL,ALERT_EMAIL,ALERT_NOTIFICATION,SHOW_CONTAINER_NO,SHOW_ITEM_ATTRIBUTES,
			DEPARTMENT_ENABLED,DIVISION_ENABLED,COMMISSION_SALARY_ENABLED, SALES_MAN_WISE_SALES;
	private double CESS_PERCENTAGE;

	private long INVENTORY_ACCOUNT, CASH_ACCOUNT,CHEQUE_ACCOUNT, SALES_TAX_ACCOUNT,
			SALES_SHIPPING_CHARGE_ACCOUNT, DEFAULT_CUSTOMER,PROFIT_ACCOUNT,LOSS_ACCOUNT;
	private long CESS_ACCOUNT, SALES_EXCISE_DUTY_ACCOUNT,
			SALES_DESCOUNT_ACCOUNT;
	private long SALES_REVENUE_ACCOUNT, PURCHASE_TAX_ACCOUNT, PURCHASE_ACCOUNT,
			PURCHASE_FOREIGN_ACCOUNT, PURCHASE_RETURN_ACCOUNT,
			PURCHASE_SHIPPING_CHARGE_ACCOUNT;
	private long PURCHASE_EXCISE_DUTY_ACCOUNT, PURCHASE_DESCOUNT_ACCOUNT,
			SALES_ACCOUNT, SALES_RETURN_ACCOUNT, CGS_ACCOUNT,
			FOREX_DIFFERENCE_ACCOUNT,CUSTOMER_GROUP,SUPPLIER_GROUP,CLEARING_AGENT_GROUP,CASH_GROUP,SALARY_ACCOUNT,
			SALARY_ADVANCE_ACCOUNT,SALARY_LOAN_ACCOUNT,SALARY_PAYABLE_ACCOUNT;

	private boolean MANUFACTURING_DATES_ENABLE, DISCOUNT_ENABLE,SALES_DISCOUNT_ENABLE,
//			EXCISE_DUTY_ENABLE, SHIPPINGCHARGEENABLE,
			FIN_YEAR_BACK_ENTRY_ENABLE, HIDE_ORGANIZATION_DETAILS,
			SHOW_ALL_EMPLOYEES_ON_PAYROLL, BARCODE_ENABLED,PURCHSE_ORDER_EXPIRY_ENABLED,
			ITEMS_IN_MULTIPLE_LANGUAGE,SHOW_SUPPLIER_SPECIFIC_ITEM_IN_PURCHASE,
			ITEM_GROUP_FILTER_IN_SALES,SALES_ORDER_FOR_SALES;
	
	

	public boolean isITEM_GROUP_FILTER_IN_SALES() {
		return ITEM_GROUP_FILTER_IN_SALES;
	}

	public void setITEM_GROUP_FILTER_IN_SALES(boolean iTEM_GROUP_FILTER_IN_SALES) {
		ITEM_GROUP_FILTER_IN_SALES = iTEM_GROUP_FILTER_IN_SALES;
	}

	public boolean isSHOW_SUPPLIER_SPECIFIC_ITEM_IN_PURCHASE() {
		return SHOW_SUPPLIER_SPECIFIC_ITEM_IN_PURCHASE;
	}

	public void setSHOW_SUPPLIER_SPECIFIC_ITEM_IN_PURCHASE(
			boolean sHOW_SUPPLIER_SPECIFIC_ITEM_IN_PURCHASE) {
		SHOW_SUPPLIER_SPECIFIC_ITEM_IN_PURCHASE = sHOW_SUPPLIER_SPECIFIC_ITEM_IN_PURCHASE;
	}

	public int getNO_OF_PRECISIONS() {
		return NO_OF_PRECISIONS;
	}

	public void setNO_OF_PRECISIONS(int nO_OF_PRECISIONS) {
		NO_OF_PRECISIONS = nO_OF_PRECISIONS;
	}

	public int getDEFAULT_DATE_SELECTION() {
		return DEFAULT_DATE_SELECTION;
	}

	public boolean isITEMS_IN_MULTIPLE_LANGUAGE() {
		return ITEMS_IN_MULTIPLE_LANGUAGE;
	}

	public void setITEMS_IN_MULTIPLE_LANGUAGE(boolean iTEMS_IN_MULTIPLE_LANGUAGE) {
		ITEMS_IN_MULTIPLE_LANGUAGE = iTEMS_IN_MULTIPLE_LANGUAGE;
	}

	public void setDEFAULT_DATE_SELECTION(int dEFAULT_DATE_SELECTION) {
		DEFAULT_DATE_SELECTION = dEFAULT_DATE_SELECTION;
	}

	public String getDATE_FORMAT() {
		return DATE_FORMAT;
	}

	public void setDATE_FORMAT(String dATE_FORMAT) {
		DATE_FORMAT = dATE_FORMAT;
	}

	public boolean isCESS_ENABLED() {
		return CESS_ENABLED;
	}

	public void setCESS_ENABLED(boolean cESS_ENABLED) {
		CESS_ENABLED = cESS_ENABLED;
	}

	public double getCESS_PERCENTAGE() {
		return CESS_PERCENTAGE;
	}

	public void setCESS_PERCENTAGE(double cESS_PERCENTAGE) {
		CESS_PERCENTAGE = cESS_PERCENTAGE;
	}

	public long getCESS_ACCOUNT() {
		return CESS_ACCOUNT;
	}

	public void setCESS_ACCOUNT(long cESS_ACCOUNT) {
		CESS_ACCOUNT = cESS_ACCOUNT;
	}

	public long getINVENTORY_ACCOUNT() {
		return INVENTORY_ACCOUNT;
	}

	public void setINVENTORY_ACCOUNT(long iNVENTORY_ACCOUNT) {
		INVENTORY_ACCOUNT = iNVENTORY_ACCOUNT;
	}

	public long getCASH_ACCOUNT() {
		return CASH_ACCOUNT;
	}

	public void setCASH_ACCOUNT(long cASH_ACCOUNT) {
		CASH_ACCOUNT = cASH_ACCOUNT;
	}

	public long getSALES_TAX_ACCOUNT() {
		return SALES_TAX_ACCOUNT;
	}

	public void setSALES_TAX_ACCOUNT(long sALES_TAX_ACCOUNT) {
		SALES_TAX_ACCOUNT = sALES_TAX_ACCOUNT;
	}

	public long getSALES_SHIPPING_CHARGE_ACCOUNT() {
		return SALES_SHIPPING_CHARGE_ACCOUNT;
	}

	public void setSALES_SHIPPING_CHARGE_ACCOUNT(
			long sALES_SHIPPING_CHARGE_ACCOUNT) {
		SALES_SHIPPING_CHARGE_ACCOUNT = sALES_SHIPPING_CHARGE_ACCOUNT;
	}

	public long getSALES_EXCISE_DUTY_ACCOUNT() {
		return SALES_EXCISE_DUTY_ACCOUNT;
	}

	public void setSALES_EXCISE_DUTY_ACCOUNT(long sALES_EXCISE_DUTY_ACCOUNT) {
		SALES_EXCISE_DUTY_ACCOUNT = sALES_EXCISE_DUTY_ACCOUNT;
	}

	public long getSALES_DESCOUNT_ACCOUNT() {
		return SALES_DESCOUNT_ACCOUNT;
	}

	public void setSALES_DESCOUNT_ACCOUNT(long sALES_DESCOUNT_ACCOUNT) {
		SALES_DESCOUNT_ACCOUNT = sALES_DESCOUNT_ACCOUNT;
	}

	public long getSALES_REVENUE_ACCOUNT() {
		return SALES_REVENUE_ACCOUNT;
	}

	public void setSALES_REVENUE_ACCOUNT(long sALES_REVENUE_ACCOUNT) {
		SALES_REVENUE_ACCOUNT = sALES_REVENUE_ACCOUNT;
	}

	public long getPURCHASE_TAX_ACCOUNT() {
		return PURCHASE_TAX_ACCOUNT;
	}

	public void setPURCHASE_TAX_ACCOUNT(long pURCHASE_TAX_ACCOUNT) {
		PURCHASE_TAX_ACCOUNT = pURCHASE_TAX_ACCOUNT;
	}

	public long getPURCHASE_SHIPPING_CHARGE_ACCOUNT() {
		return PURCHASE_SHIPPING_CHARGE_ACCOUNT;
	}

	public void setPURCHASE_SHIPPING_CHARGE_ACCOUNT(
			long pURCHASE_SHIPPING_CHARGE_ACCOUNT) {
		PURCHASE_SHIPPING_CHARGE_ACCOUNT = pURCHASE_SHIPPING_CHARGE_ACCOUNT;
	}

	public long getPURCHASE_EXCISE_DUTY_ACCOUNT() {
		return PURCHASE_EXCISE_DUTY_ACCOUNT;
	}

	public void setPURCHASE_EXCISE_DUTY_ACCOUNT(
			long pURCHASE_EXCISE_DUTY_ACCOUNT) {
		PURCHASE_EXCISE_DUTY_ACCOUNT = pURCHASE_EXCISE_DUTY_ACCOUNT;
	}

	public long getPURCHASE_DESCOUNT_ACCOUNT() {
		return PURCHASE_DESCOUNT_ACCOUNT;
	}

	public void setPURCHASE_DESCOUNT_ACCOUNT(long pURCHASE_DESCOUNT_ACCOUNT) {
		PURCHASE_DESCOUNT_ACCOUNT = pURCHASE_DESCOUNT_ACCOUNT;
	}

	public long getCGS_ACCOUNT() {
		return CGS_ACCOUNT;
	}

	public void setCGS_ACCOUNT(long cGS_ACCOUNT) {
		CGS_ACCOUNT = cGS_ACCOUNT;
	}

	public long getFOREX_DIFFERENCE_ACCOUNT() {
		return FOREX_DIFFERENCE_ACCOUNT;
	}

	public void setFOREX_DIFFERENCE_ACCOUNT(long fOREX_DIFFERENCE_ACCOUNT) {
		FOREX_DIFFERENCE_ACCOUNT = fOREX_DIFFERENCE_ACCOUNT;
	}

	public boolean isTAX_ENABLED() {
		return TAX_ENABLED;
	}

	public void setTAX_ENABLED(boolean tAX_ENABLED) {
		TAX_ENABLED = tAX_ENABLED;
	}

	public boolean isMANUFACTURING_DATES_ENABLE() {
		return MANUFACTURING_DATES_ENABLE;
	}

	public void setMANUFACTURING_DATES_ENABLE(boolean mANUFACTURING_DATES_ENABLE) {
		MANUFACTURING_DATES_ENABLE = mANUFACTURING_DATES_ENABLE;
	}

	public boolean isDISCOUNT_ENABLE() {
		return DISCOUNT_ENABLE;
	}

	public void setDISCOUNT_ENABLE(boolean dISCOUNT_ENABLE) {
		DISCOUNT_ENABLE = dISCOUNT_ENABLE;
	}

//	public boolean isEXCISE_DUTY_ENABLE() {
//		return EXCISE_DUTY_ENABLE;
//	}
//
//	public void setEXCISE_DUTY_ENABLE(boolean eXCISE_DUTY_ENABLE) {
//		EXCISE_DUTY_ENABLE = eXCISE_DUTY_ENABLE;
//	}
//
//	public boolean isSHIPPINGCHARGEENABLE() {
//		return SHIPPINGCHARGEENABLE;
//	}
//
//	public void setSHIPPINGCHARGEENABLE(boolean sHIPPINGCHARGEENABLE) {
//		SHIPPINGCHARGEENABLE = sHIPPINGCHARGEENABLE;
//	}

	public long getPURCHASE_ACCOUNT() {
		return PURCHASE_ACCOUNT;
	}

	public void setPURCHASE_ACCOUNT(long pURCHASE_ACCOUNT) {
		PURCHASE_ACCOUNT = pURCHASE_ACCOUNT;
	}

	public boolean isFIN_YEAR_BACK_ENTRY_ENABLE() {
		return FIN_YEAR_BACK_ENTRY_ENABLE;
	}

	public void setFIN_YEAR_BACK_ENTRY_ENABLE(boolean fIN_YEAR_BACK_ENTRY_ENABLE) {
		FIN_YEAR_BACK_ENTRY_ENABLE = fIN_YEAR_BACK_ENTRY_ENABLE;
	}

	public int getSTOCK_MANAGEMENT() {
		return STOCK_MANAGEMENT;
	}

	public void setSTOCK_MANAGEMENT(int sTOCK_MANAGEMENT) {
		STOCK_MANAGEMENT = sTOCK_MANAGEMENT;
	}

	public boolean isHIDE_ORGANIZATION_DETAILS() {
		return HIDE_ORGANIZATION_DETAILS;
	}

	public void setHIDE_ORGANIZATION_DETAILS(boolean hIDE_ORGANIZATION_DETAILS) {
		HIDE_ORGANIZATION_DETAILS = hIDE_ORGANIZATION_DETAILS;
	}

	public int getEXPENDETURE_SHOW_ACCOUNTS() {
		return EXPENDETURE_SHOW_ACCOUNTS;
	}

	public void setEXPENDETURE_SHOW_ACCOUNTS(int eXPENDETURE_SHOW_ACCOUNTS) {
		EXPENDETURE_SHOW_ACCOUNTS = eXPENDETURE_SHOW_ACCOUNTS;
	}

	public boolean isSHOW_ALL_EMPLOYEES_ON_PAYROLL() {
		return SHOW_ALL_EMPLOYEES_ON_PAYROLL;
	}

	public void setSHOW_ALL_EMPLOYEES_ON_PAYROLL(
			boolean sHOW_ALL_EMPLOYEES_ON_PAYROLL) {
		SHOW_ALL_EMPLOYEES_ON_PAYROLL = sHOW_ALL_EMPLOYEES_ON_PAYROLL;
	}

	public String getSYSTEM_EMAIL_PASSWORD() {
		return SYSTEM_EMAIL_PASSWORD;
	}

	public void setSYSTEM_EMAIL_PASSWORD(String sYSTEM_EMAIL_PASSWORD) {
		SYSTEM_EMAIL_PASSWORD = sYSTEM_EMAIL_PASSWORD;
	}

	public String getSYSTEM_EMAIL() {
		return SYSTEM_EMAIL;
	}

	public void setSYSTEM_EMAIL(String sYSTEM_EMAIL) {
		SYSTEM_EMAIL = sYSTEM_EMAIL;
	}

	public String getSALES_EMAIL_PASSWORD() {
		return SALES_EMAIL_PASSWORD;
	}

	public void setSALES_EMAIL_PASSWORD(String sALES_EMAIL_PASSWORD) {
		SALES_EMAIL_PASSWORD = sALES_EMAIL_PASSWORD;
	}

	public String getSALES_EMAIL() {
		return SALES_EMAIL;
	}

	public void setSALES_EMAIL(String sALES_EMAIL) {
		SALES_EMAIL = sALES_EMAIL;
	}

	public boolean isBARCODE_ENABLED() {
		return BARCODE_ENABLED;
	}

	public void setBARCODE_ENABLED(boolean bARCODE_ENABLED) {
		BARCODE_ENABLED = bARCODE_ENABLED;
	}

	public long getSALES_ACCOUNT() {
		return SALES_ACCOUNT;
	}

	public void setSALES_ACCOUNT(long sALES_ACCOUNT) {
		SALES_ACCOUNT = sALES_ACCOUNT;
	}

	public long getPURCHASE_RETURN_ACCOUNT() {
		return PURCHASE_RETURN_ACCOUNT;
	}

	public void setPURCHASE_RETURN_ACCOUNT(long pURCHASE_RETURN_ACCOUNT) {
		PURCHASE_RETURN_ACCOUNT = pURCHASE_RETURN_ACCOUNT;
	}

	public long getSALES_RETURN_ACCOUNT() {
		return SALES_RETURN_ACCOUNT;
	}

	public void setSALES_RETURN_ACCOUNT(long sALES_RETURN_ACCOUNT) {
		SALES_RETURN_ACCOUNT = sALES_RETURN_ACCOUNT;
	}

	public long getDEFAULT_CUSTOMER() {
		return DEFAULT_CUSTOMER;
	}

	public void setDEFAULT_CUSTOMER(long dEFAULT_CUSTOMER) {
		DEFAULT_CUSTOMER = dEFAULT_CUSTOMER;
	}

	public boolean isKEEP_DELETED_DATA() {
		return KEEP_DELETED_DATA;
	}

	public void setKEEP_DELETED_DATA(boolean kEEP_DELETED_DATA) {
		KEEP_DELETED_DATA = kEEP_DELETED_DATA;
	}

	public boolean isSALE_PRICE_EDITABLE() {
		return SALE_PRICE_EDITABLE;
	}

	public void setSALE_PRICE_EDITABLE(boolean sALE_PRICE_EDITABLE) {
		SALE_PRICE_EDITABLE = sALE_PRICE_EDITABLE;
	}

	public boolean isPAYMENT_BILL_SELECTION_MANDATORY() {
		return PAYMENT_BILL_SELECTION_MANDATORY;
	}

	public void setPAYMENT_BILL_SELECTION_MANDATORY(
			boolean pAYMENT_BILL_SELECTION_MANDATORY) {
		PAYMENT_BILL_SELECTION_MANDATORY = pAYMENT_BILL_SELECTION_MANDATORY;
	}

	public boolean isDISABLE_SALES_FOR_CUSTOMERS_UNDER_CR_LIMIT() {
		return DISABLE_SALES_FOR_CUSTOMERS_UNDER_CR_LIMIT;
	}

	public void setDISABLE_SALES_FOR_CUSTOMERS_UNDER_CR_LIMIT(
			boolean dISABLE_SALES_FOR_CUSTOMERS_UNDER_CR_LIMIT) {
		DISABLE_SALES_FOR_CUSTOMERS_UNDER_CR_LIMIT = dISABLE_SALES_FOR_CUSTOMERS_UNDER_CR_LIMIT;
	}

	public boolean isAUTO_CREATE_SUBGROUP_CODE() {
		return AUTO_CREATE_SUBGROUP_CODE;
	}

	public void setAUTO_CREATE_SUBGROUP_CODE(boolean aUTO_CREATE_SUBGROUP_CODE) {
		AUTO_CREATE_SUBGROUP_CODE = aUTO_CREATE_SUBGROUP_CODE;
	}

	public boolean isUSE_SALES_NO_IN_SALES_ORDER() {
		return USE_SALES_NO_IN_SALES_ORDER;
	}

	public void setUSE_SALES_NO_IN_SALES_ORDER(
			boolean uSE_SALES_NO_IN_SALES_ORDER) {
		USE_SALES_NO_IN_SALES_ORDER = uSE_SALES_NO_IN_SALES_ORDER;
	}

	public boolean isUSE_SYSTEM_MAIL_FOR_SEND_CUSTOMERMAIL() {
		return USE_SYSTEM_MAIL_FOR_SEND_CUSTOMERMAIL;
	}

	public void setUSE_SYSTEM_MAIL_FOR_SEND_CUSTOMERMAIL(
			boolean uSE_SYSTEM_MAIL_FOR_SEND_CUSTOMERMAIL) {
		USE_SYSTEM_MAIL_FOR_SEND_CUSTOMERMAIL = uSE_SYSTEM_MAIL_FOR_SEND_CUSTOMERMAIL;
	}

	public boolean isKEEP_OTHER_WINDOWS() {
		return KEEP_OTHER_WINDOWS;
	}

	public void setKEEP_OTHER_WINDOWS(boolean kEEP_OTHER_WINDOWS) {
		KEEP_OTHER_WINDOWS = kEEP_OTHER_WINDOWS;
	}

	public boolean isHIDE_ALERTS() {
		return HIDE_ALERTS;
	}

	public void setHIDE_ALERTS(boolean hIDE_ALERTS) {
		HIDE_ALERTS = hIDE_ALERTS;
	}

	public boolean isGRADING_ENABLED() {
		return GRADING_ENABLED;
	}

	public void setGRADING_ENABLED(boolean gRADING_ENABLED) {
		GRADING_ENABLED = gRADING_ENABLED;
	}

//	public boolean isLOCAL_FOREIGN_TYPE_ENABLED() {
//		return LOCAL_FOREIGN_TYPE_ENABLED;
//	}
//
//	public void setLOCAL_FOREIGN_TYPE_ENABLED(boolean lOCAL_FOREIGN_TYPE_ENABLED) {
//		LOCAL_FOREIGN_TYPE_ENABLED = lOCAL_FOREIGN_TYPE_ENABLED;
//	}

	public long getPURCHASE_FOREIGN_ACCOUNT() {
		return PURCHASE_FOREIGN_ACCOUNT;
	}

	public void setPURCHASE_FOREIGN_ACCOUNT(long pURCHASE_FOREIGN_ACCOUNT) {
		PURCHASE_FOREIGN_ACCOUNT = pURCHASE_FOREIGN_ACCOUNT;
	}

	public boolean isRACK_ENABLED() {
		return RACK_ENABLED;
	}

	public void setRACK_ENABLED(boolean rACK_ENABLED) {
		RACK_ENABLED = rACK_ENABLED;
	}

	public boolean isUSE_GROSS_AND_NET_WEIGHT() {
		return USE_GROSS_AND_NET_WEIGHT;
	}

	public void setUSE_GROSS_AND_NET_WEIGHT(boolean uSE_GROSS_AND_NET_WEIGHT) {
		USE_GROSS_AND_NET_WEIGHT = uSE_GROSS_AND_NET_WEIGHT;
	}

	public boolean isMULTIPLE_CURRENCY_ENABLED() {
		return MULTIPLE_CURRENCY_ENABLED;
	}

	public void setMULTIPLE_CURRENCY_ENABLED(boolean mULTIPLE_CURRENCY_ENABLED) {
		MULTIPLE_CURRENCY_ENABLED = mULTIPLE_CURRENCY_ENABLED;
	}

	public boolean isUSE_SALES_RATE_FROM_STOCK() {
		return USE_SALES_RATE_FROM_STOCK;
	}

	public void setUSE_SALES_RATE_FROM_STOCK(boolean uSE_SALES_RATE_FROM_STOCK) {
		USE_SALES_RATE_FROM_STOCK = uSE_SALES_RATE_FROM_STOCK;
	}

	public int getUPDATE_RATE_AND_CONV_QTY() {
		return UPDATE_RATE_AND_CONV_QTY;
	}

	public void setUPDATE_RATE_AND_CONV_QTY(int uPDATE_RATE_AND_CONV_QTY) {
		UPDATE_RATE_AND_CONV_QTY = uPDATE_RATE_AND_CONV_QTY;
	}

	public int getCURRENCY_FORMAT() {
		return CURRENCY_FORMAT;
	}

	public void setCURRENCY_FORMAT(int cURRENCY_FORMAT) {
		CURRENCY_FORMAT = cURRENCY_FORMAT;
	}

	public boolean isSHOW_STOCK_IN_PROFIT_REPORT() {
		return SHOW_STOCK_IN_PROFIT_REPORT;
	}

	public void setSHOW_STOCK_IN_PROFIT_REPORT(
			boolean sHOW_STOCK_IN_PROFIT_REPORT) {
		SHOW_STOCK_IN_PROFIT_REPORT = sHOW_STOCK_IN_PROFIT_REPORT;
	}

	public String getSYSTEM_EMAIL_HOST() {
		return SYSTEM_EMAIL_HOST;
	}

	public void setSYSTEM_EMAIL_HOST(String sYSTEM_EMAIL_HOST) {
		SYSTEM_EMAIL_HOST = sYSTEM_EMAIL_HOST;
	}

	public String getSALES_EMAIL_HOST() {
		return SALES_EMAIL_HOST;
	}

	public void setSALES_EMAIL_HOST(String sALES_EMAIL_HOST) {
		SALES_EMAIL_HOST = sALES_EMAIL_HOST;
	}

	public int getTHEME() {
		return THEME;
	}

	public void setTHEME(int tHEME) {
		THEME = tHEME;
	}

	public boolean isSALES_NO_CREATION_MANUAL() {
		return SALES_NO_CREATION_MANUAL;
	}

	public void setSALES_NO_CREATION_MANUAL(boolean sALES_NO_CREATION_MANUAL) {
		SALES_NO_CREATION_MANUAL = sALES_NO_CREATION_MANUAL;
	}

	public boolean isALERT_EMAIL() {
		return ALERT_EMAIL;
	}

	public void setALERT_EMAIL(boolean aLERT_EMAIL) {
		ALERT_EMAIL = aLERT_EMAIL;
	}

	public boolean isALERT_NOTIFICATION() {
		return ALERT_NOTIFICATION;
	}

	public void setALERT_NOTIFICATION(boolean aLERT_NOTIFICATION) {
		ALERT_NOTIFICATION = aLERT_NOTIFICATION;
	}

	public String getALERT_EMAILIDS() {
		return ALERT_EMAILIDS;
	}

	public void setALERT_EMAILIDS(String aLERT_EMAILIDS) {
		ALERT_EMAILIDS = aLERT_EMAILIDS;
	}

	public String getAPPLICATION_EMAIL() {
		return APPLICATION_EMAIL;
	}

	public void setAPPLICATION_EMAIL(String aPPLICATION_EMAIL) {
		APPLICATION_EMAIL = aPPLICATION_EMAIL;
	}

	public String getAPPLICATION_EMAIL_HOST() {
		return APPLICATION_EMAIL_HOST;
	}

	public void setAPPLICATION_EMAIL_HOST(String aPPLICATION_EMAIL_HOST) {
		APPLICATION_EMAIL_HOST = aPPLICATION_EMAIL_HOST;
	}

	public String getAPPLICATION_EMAIL_PASSWORD() {
		return APPLICATION_EMAIL_PASSWORD;
	}

	public void setAPPLICATION_EMAIL_PASSWORD(String aPPLICATION_EMAIL_PASSWORD) {
		APPLICATION_EMAIL_PASSWORD = aPPLICATION_EMAIL_PASSWORD;
	}

	public boolean isALERT_FOR_UNDER_CREDIT_LIMIT() {
		return ALERT_FOR_UNDER_CREDIT_LIMIT;
	}

	public void setALERT_FOR_UNDER_CREDIT_LIMIT(boolean aLERT_FOR_UNDER_CREDIT_LIMIT) {
		ALERT_FOR_UNDER_CREDIT_LIMIT = aLERT_FOR_UNDER_CREDIT_LIMIT;
	}

	public boolean isSHOW_CONTAINER_NO() {
		return SHOW_CONTAINER_NO;
	}

	public void setSHOW_CONTAINER_NO(boolean sHOW_CONTAINER_NO) {
		SHOW_CONTAINER_NO = sHOW_CONTAINER_NO;
	}

	public boolean isSHOW_ITEM_ATTRIBUTES() {
		return SHOW_ITEM_ATTRIBUTES;
	}

	public void setSHOW_ITEM_ATTRIBUTES(boolean sHOW_ITEM_ATTRIBUTES) {
		SHOW_ITEM_ATTRIBUTES = sHOW_ITEM_ATTRIBUTES;
	}

	public boolean isDEPARTMENT_ENABLED() {
		return DEPARTMENT_ENABLED;
	}

	public void setDEPARTMENT_ENABLED(boolean dEPARTMENT_ENABLED) {
		DEPARTMENT_ENABLED = dEPARTMENT_ENABLED;
	}

	public boolean isDIVISION_ENABLED() {
		return DIVISION_ENABLED;
	}

	public void setDIVISION_ENABLED(boolean dIVISION_ENABLED) {
		DIVISION_ENABLED = dIVISION_ENABLED;
	}

	public long getCUSTOMER_GROUP() {
		return CUSTOMER_GROUP;
	}

	public void setCUSTOMER_GROUP(long cUSTOMER_GROUP) {
		CUSTOMER_GROUP = cUSTOMER_GROUP;
	}

	public long getSUPPLIER_GROUP() {
		return SUPPLIER_GROUP;
	}

	public void setSUPPLIER_GROUP(long sUPPLIER_GROUP) {
		SUPPLIER_GROUP = sUPPLIER_GROUP;
	}

	public long getCLEARING_AGENT_GROUP() {
		return CLEARING_AGENT_GROUP;
	}

	public void setCLEARING_AGENT_GROUP(long cLEARING_AGENT_GROUP) {
		CLEARING_AGENT_GROUP = cLEARING_AGENT_GROUP;
	}

	public long getCASH_GROUP() {
		return CASH_GROUP;
	}

	public void setCASH_GROUP(long cASH_GROUP) {
		CASH_GROUP = cASH_GROUP;
	}

	public long getCHEQUE_ACCOUNT() {
		return CHEQUE_ACCOUNT;
	}

	public void setCHEQUE_ACCOUNT(long cHEQUE_ACCOUNT) {
		CHEQUE_ACCOUNT = cHEQUE_ACCOUNT;
	}

	public boolean isAUTO_CREATE_CUSTOMER_CODE() {
		return AUTO_CREATE_CUSTOMER_CODE;
	}

	public void setAUTO_CREATE_CUSTOMER_CODE(boolean aUTO_CREATE_CUSTOMER_CODE) {
		AUTO_CREATE_CUSTOMER_CODE = aUTO_CREATE_CUSTOMER_CODE;
	}

	public boolean isAUTO_CREATE_SUPPLIER_CODE() {
		return AUTO_CREATE_SUPPLIER_CODE;
	}

	public void setAUTO_CREATE_SUPPLIER_CODE(boolean aUTO_CREATE_SUPPLIER_CODE) {
		AUTO_CREATE_SUPPLIER_CODE = aUTO_CREATE_SUPPLIER_CODE;
	}

	public int getPROFIT_CALCULATION() {
		return PROFIT_CALCULATION;
	}

	public void setPROFIT_CALCULATION(int pROFIT_CALCULATION) {
		PROFIT_CALCULATION = pROFIT_CALCULATION;
	}

	public int getBARCODE_TYPE() {
		return BARCODE_TYPE;
	}

	public void setBARCODE_TYPE(int bARCODE_TYPE) {
		BARCODE_TYPE = bARCODE_TYPE;
	}

	public long getPROFIT_ACCOUNT() {
		return PROFIT_ACCOUNT;
	}

	public void setPROFIT_ACCOUNT(long pROFIT_ACCOUNT) {
		PROFIT_ACCOUNT = pROFIT_ACCOUNT;
	}

	public long getLOSS_ACCOUNT() {
		return LOSS_ACCOUNT;
	}

	public void setLOSS_ACCOUNT(long lOSS_ACCOUNT) {
		LOSS_ACCOUNT = lOSS_ACCOUNT;
	}

	public boolean isCOMMISSION_SALARY_ENABLED() {
		return COMMISSION_SALARY_ENABLED;
	}

	public void setCOMMISSION_SALARY_ENABLED(boolean cOMMISSION_SALARY_ENABLED) {
		COMMISSION_SALARY_ENABLED = cOMMISSION_SALARY_ENABLED;
	}

	public long getSALARY_ACCOUNT() {
		return SALARY_ACCOUNT;
	}

	public void setSALARY_ACCOUNT(long sALARY_ACCOUNT) {
		SALARY_ACCOUNT = sALARY_ACCOUNT;
	}

	public long getSALARY_ADVANCE_ACCOUNT() {
		return SALARY_ADVANCE_ACCOUNT;
	}

	public void setSALARY_ADVANCE_ACCOUNT(long sALARY_ADVANCE_ACCOUNT) {
		SALARY_ADVANCE_ACCOUNT = sALARY_ADVANCE_ACCOUNT;
	}

	public long getSALARY_LOAN_ACCOUNT() {
		return SALARY_LOAN_ACCOUNT;
	}

	public void setSALARY_LOAN_ACCOUNT(long sALARY_LOAN_ACCOUNT) {
		SALARY_LOAN_ACCOUNT = sALARY_LOAN_ACCOUNT;
	}

	public long getSALARY_PAYABLE_ACCOUNT() {
		return SALARY_PAYABLE_ACCOUNT;
	}

	public void setSALARY_PAYABLE_ACCOUNT(long sALARY_PAYABLE_ACCOUNT) {
		SALARY_PAYABLE_ACCOUNT = sALARY_PAYABLE_ACCOUNT;
	}

	public boolean isSALES_MAN_WISE_SALES() {
		return SALES_MAN_WISE_SALES;
	}

	public void setSALES_MAN_WISE_SALES(boolean sALES_MAN_WISE_SALES) {
		SALES_MAN_WISE_SALES = sALES_MAN_WISE_SALES;
	}

	public boolean isPURCHSE_ORDER_EXPIRY_ENABLED() {
		return PURCHSE_ORDER_EXPIRY_ENABLED;
	}

	public void setPURCHSE_ORDER_EXPIRY_ENABLED(boolean pURCHSE_ORDER_EXPIRY_ENABLED) {
		PURCHSE_ORDER_EXPIRY_ENABLED = pURCHSE_ORDER_EXPIRY_ENABLED;
	}

	public boolean isSALES_DISCOUNT_ENABLE() {
		return SALES_DISCOUNT_ENABLE;
	}

	public void setSALES_DISCOUNT_ENABLE(boolean sALES_DISCOUNT_ENABLE) {
		SALES_DISCOUNT_ENABLE = sALES_DISCOUNT_ENABLE;
	}

	public boolean isSALES_ORDER_FOR_SALES() {
		return SALES_ORDER_FOR_SALES;
	}

	public void setSALES_ORDER_FOR_SALES(boolean sALES_ORDER_FOR_SALES) {
		SALES_ORDER_FOR_SALES = sALES_ORDER_FOR_SALES;
	}

	public int getPAYROLL_CALCULATION() {
		return PAYROLL_CALCULATION;
	}

	public void setPAYROLL_CALCULATION(int pAYROLL_CALCULATION) {
		PAYROLL_CALCULATION = pAYROLL_CALCULATION;
	}
	
}
